cmake_minimum_required(VERSION 3.20)
project(imgui)
file(GLOB SRC imgui/*.cpp imgui/backends/imgui_impl_glfw.cpp imgui/backends/imgui_impl_opengl3.cpp) 
add_library(imgui STATIC ${SRC})
target_link_libraries(imgui PUBLIC glfw)
target_include_directories(imgui PUBLIC ./imgui)
